module fos {
  module dds {
    module types {
      
      struct KeyValue {
	long version;
	string key;
	string value;
	string sid;	
      };
      #pragma keylist KeyValue key

      
      struct StoreInfo {
	string sid;
	string sroot;
	string shome;
      };
      #pragma keylist StoreInfo sid
      
      struct Resolve {
        string source_sid;
        string key;
      };
      #pragma keylist Resolve key

      
    };
  };
};
