module fos {
  module dds {
    module types {

      
      struct KeyValue {
	    string key;
	    string value;
	    unsigned long long revision;
	    string store_id;
      };
      #pragma keylist KeyValue key


      struct StoreInfo {
	    string store_id;
	    string sroot;
	    string shome;
      };
      #pragma keylist StoreInfo store_id

      struct Resolve {
        string source_store_id;
        string key;
      };
      #pragma keylist Resolve

      
    };
  };
};
